name: BadlandsCaves
version: ${project.version}
main: me.fullpotato.badlandscaves.badlandscaves.BadlandsCaves
api-version: 1.13
depend:
  - ProtocolLib
commands:
  thirst:
    usage: /thirst <get|set> <username> <value>
    description: Work with Thirst
  toxicity:
    usage: /toxicity <get|set> <username> <value>
    description: Work with Toxicity
    aliases: tox
  deaths:
    usage: /deaths <get|set> <username> <value>
    description: Work with Death count
    aliases: death
  hardmode:
    usage: /hardmode <get|set> <value>
    description: Work with Hardmode value
    aliases: hm